services:
  - type: web
    name: TonjamBot
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: "7591465695:AAFMdgh2tCD7nNvLG2DrODjy7wg8MvEWVoA"
      - key: WEBHOOK_URL
        value: "https://tonjambot.onrender.com"  # Update to your Render URL
      - key: PORT
        value: 8443
    autoDeploy: true
